### ISSUE TITLE
How to handle coordinate conversion should be written in the docs

### ISSUE THREAD

**Issue by temeddix** [3liz/proj4rs#1]
```rust
// EPSG:5174 is used by Korean government's open data.
let epsg_5174 = Proj::from_proj_string(concat!(
    "+proj=tmerc +lat_0=38 +lon_0=127.002890277778",
    " +k=1 +x_0=200000 +y_0=500000 +ellps=bessel",
    " +towgs84=-145.907,505.034,685.756,-1.162,2.347,1.592,6.342",
    " +units=m +no_defs +type=crs"
))
.unwrap();
// EPSG:4326 is WGS84, known to us as basic longitude and latitude.
let epsg_4326 = Proj::from_proj_string(concat!(
    "+proj=longlat +ellps=WGS84",
    " +datum=WGS84 +no_defs"
))
.unwrap();
let mut point_3d = (point.x(), point.y(), 0.0);
proj4rs::transform::transform(&epsg_5174, &epsg_4326, &mut point_3d).unwrap();
vector.push((point_3d.0, point_3d.1));
```

Would this kind of operation work as expected in the current status of this library? I did some tests and numbers seemed to be a bit broken

**Comment by dmarteau** [comment]
What is the tests did you performs ? What are the results ?

A good idea is to compare with what gives the original proj9 for the same transformations.

**Comment by temeddix** [comment]
This is part of the `println!` output:

```
Input
[Point(Coord { x: 198236.3200000003, y: 453407.8560000006
    }), Point(Coord { x: 198227.483, y: 453393.5999999996
    }), Point(Coord { x: 198225.35199999996, y: 453389.6490000002
    }), Point(Coord { x: 198214.6950000003, y: 453395.3139999993
    }), Point(Coord { x: 198226.38499999978, y: 453414.2899999991
    }), Point(Coord { x: 198227.67399999965, y: 453413.33999999985
    }), Point(Coord { x: 198236.3200000003, y: 453407.8560000006
    })
]

Output
[(2.21623124501456,
    0.6559485823594712), (2.21622949957796,
    0.6559463402438963), (2.216229078700797,
    0.6559457188618371), (2.216226972652845,
    0.6559466092635431), (2.216229281588784,
    0.655949593717786), (2.2162295363360927,
    0.6559494443806742), (2.21623124501456,
    0.6559485823594712)
]
```

I'm using Korean government's land data, and although I'm not using proj9.2 directly, I'm checking the values and data with QGIS and deck.gl. Since this is a polygon representing a land in South Korea, it should have longitude and latitude something like +127, +37. The land data file itself(SHP) seems to be correct because it's being opened in QGIS and deck.gl without any problems.

<img width="935" alt="image" src="https://github.com/3liz/proj4rs/assets/66480156/5794004e-5a41-442e-a336-586b29c94d48">

**Comment by dmarteau** [comment]
Angular input/output values are expressed in radians: you have to convert your result in degrees:

i.e (2.21623124501456, 0.6559485823594712) radians -> (126.98069676435814, 37.58308534678718) degres

**Comment by dmarteau** [comment]
Note that in the définition  `+proj=longlat +ellps=WGS84 +datum=WGS84` the `+ellps=WGS84` is redondant since WGS84 datum implies WGS84 ellipsoid.

**Comment by temeddix** [comment]
I see, thanks! It's amazing this project handles complex ellipsoid conversions this easily. May I make PRs related to improving docs including examples and usages for other people to use this more easily?

**Comment by temeddix** [comment]
<img width="954" alt="image" src="https://github.com/3liz/proj4rs/assets/66480156/718c9832-a062-41d4-a124-d61a0e844017">

Hmm, there seems to be a numerical error... About 0.4degrees are different. Is this because of some ellipsoid conversion problem?

**Comment by dmarteau** [comment]
> It's amazing that this project handles complex ellipsoid conversions this easily

Credits should be given to the original [`Proj` project](https://github.com/OSGeo/PROJ) from which the original projection algorithms  come from.  As stated, this project is mostly an attempt to create pure Rust implementation of the original proj4 code with some improvement of how to handle i/o data and easy to use with WASM.

> May I make PRs related to improving docs including examples and usages for other people that might use this library?

You are welcome !

**Comment by temeddix** [comment]
I'm totally into making pure Rust implementation of proj4. There was `proj` crate that binds with C `libproj9.2`, but it's very hacky and even installing basic dependencies didn't work properly. Happy to have this crate :)
