### ISSUE TITLE
WIP: aeqd projection

### ISSUE THREAD

**Issue by btdevine** [3liz/proj4rs#14]
Hi all,

First off, thanks for this awesome crate! We have a specific use case for the `aeqd` projection, so I just wanted to let people know (to avoid potentially conflicting work) that I'm currently working on a port, and hope to have a PR opened in the next couple of days.

Best,

Brendan

**Comment by btdevine** [comment]
Update on this: unfortunately, this looks like a lot more work than I initially expected. The inclusion of the `geod_inverse` function would require porting a lot of the `geodesic.c` file, which is more than I have time for right now. Going to close this for now.

**Comment by dmarteau** [comment]
Hi, It appears to me that the geodesic port could (should ?) be a crate of its own.

**Comment by dmarteau** [comment]
Is a matter of fact, the plan is to keep the core as slim as possible and include less or used projection as optional depdendencies. 
(one of the goal this library is to provide an efficient WASM module that cover the basic cartographic usages).

**Comment by dmarteau** [comment]
FYI: aeqd is finally implemented with bfa68f75f44734a2d145d0e5e2f0f96199f2aed3. 

It uses C static binding from a subpart of the `geodesic` library and, atm,  this prevents using the aeqd in WASM: I need to investigate  a solution by using a js binding to the js port of the Geodesic library as used in Proj4js (https://www.npmjs.com/package/geographiclib-geodesic)
