### ISSUE TITLE
Confliction WASM main if used as dependency.

### ISSUE THREAD

**Issue by antonWetzel** [3liz/proj4rs#15]
If this is used as a dependency in a rust project with a separate `wasm_bindgen(start)` the ```error: cannot specify two `start` functions``` is produced.

## Solutions

- move `wasm_bindgen(start)` into another crate
- or make `wasm_bindgen(start)` optional
  - no clue if default disabled or enabled is desired

**Comment by dmarteau** [comment]
@antonWetzel Could you test with #17 please ?  

The entrypoint is the default (keep the actual behavior), so disable defaults for using as wasm dependency.

**Comment by antonWetzel** [comment]
Tested 
```toml
proj4rs = { git = "https://github.com/3liz/proj4rs.git", rev = "ff41d42", default-features = false }
```

Works as a dependency on native and wasm without problems.
