### ISSUE TITLE
Wrong conversion from EPSG:4326 to EPSG:3035

### ISSUE THREAD

**Issue by gschulze** [3liz/proj4rs#18]
When converting the coordinate

(15.4213696, 47.0766716)

using proj4rs, I get

(**4732659.0**427561561, **2677**130.1353262868)

as output. Doing the same transformation with epsg.io yields

(**4732659.0**503001185, **2677**630.551830157)

Whereas the difference in the x-coordinate might be attributed to rounding errors, the y-coordinate is off by a few hundred meters. I checked with the official regional statistical grid units for Austria (https://www.data.gv.at/katalog/dataset/stat_regionalstatistische-rastereinheiten66c96), and the corresponding raster cell agrees with the latter.

**Comment by dmarteau** [comment]
proj4rs use projstrings definitions: can you gives the projstrings definition used  in both cases ?

**Comment by gschulze** [comment]
Sorry, my bad. I forgot to mention it in the issue. the projection used is ETRS89-extended / LAEA Europe (EPSG:3035):

```
+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs
```

**Comment by dmarteau** [comment]
I have found the error in the laea  projection, now results for `(15.4213696, 47.0766716)` are:

* With proj4rs: `(4732659.007426266,  2677630.7269610995)`
* With proj 8.2.1:  `(4732659.0074262656,   2677630.7269610995)`  - computed with `echo "15.4213696 47.0766716"  |  cs2cs -d 10 +init=epsg:4326 +to +init=epsg:3035`

To be compared to your result from epsg.io: `(4732659.0427561561, 2677130.1353262868)`

Good catch !  Thanks !

**Comment by gschulze** [comment]
Thanks for the quick fix!
