### ISSUE TITLE
`crates.io` explanation is outdated

### ISSUE THREAD

**Issue by temeddix** [3liz/proj4rs#4]
The first `README.md` is where users get a grasp of what this library does, how it works, and how to use it. I've noticed that the package description in `crates.io` is not updated after a few weeks since guides were improved. Can this crate be published with the updated guides as `0.1.1`?

<img width="711" alt="image" src="https://github.com/3liz/proj4rs/assets/66480156/3b1f7718-575a-45c3-9609-9a4b19628cc0">
<img width="811" alt="image" src="https://github.com/3liz/proj4rs/assets/66480156/3163af7c-7192-4ce4-9748-4419d8a6dfce">

**Comment by dmarteau** [comment]
Published version 0.1.1
